global:
  scrape_interval: 5s # Scrape often for testing

scrape_configs:
  - job_name: "node_app"
    static_configs:
      - targets: ["gateway:3000"] # 'myapp' matches the service name in docker-compose
